#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIURO_PROJEKT.App_Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="API")]
	public partial class BIURODataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCENNIK(CENNIK instance);
    partial void UpdateCENNIK(CENNIK instance);
    partial void DeleteCENNIK(CENNIK instance);
    partial void InsertZLECENIE(ZLECENIE instance);
    partial void UpdateZLECENIE(ZLECENIE instance);
    partial void DeleteZLECENIE(ZLECENIE instance);
    partial void InsertRZECZOZNAWCA(RZECZOZNAWCA instance);
    partial void UpdateRZECZOZNAWCA(RZECZOZNAWCA instance);
    partial void DeleteRZECZOZNAWCA(RZECZOZNAWCA instance);
    #endregion
		
		public BIURODataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["APIConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BIURODataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BIURODataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BIURODataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BIURODataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CENNIK> CENNIK
		{
			get
			{
				return this.GetTable<CENNIK>();
			}
		}
		
		public System.Data.Linq.Table<ZLECENIE> ZLECENIE
		{
			get
			{
				return this.GetTable<ZLECENIE>();
			}
		}
		
		public System.Data.Linq.Table<RZECZOZNAWCA> RZECZOZNAWCA
		{
			get
			{
				return this.GetTable<RZECZOZNAWCA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CENNIK")]
	public partial class CENNIK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TYP;
		
		private System.Nullable<decimal> _CENA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTYPChanging(string value);
    partial void OnTYPChanged();
    partial void OnCENAChanging(System.Nullable<decimal> value);
    partial void OnCENAChanged();
    #endregion
		
		public CENNIK()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYP", DbType="VarChar(70)")]
		public string TYP
		{
			get
			{
				return this._TYP;
			}
			set
			{
				if ((this._TYP != value))
				{
					this.OnTYPChanging(value);
					this.SendPropertyChanging();
					this._TYP = value;
					this.SendPropertyChanged("TYP");
					this.OnTYPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CENA", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> CENA
		{
			get
			{
				return this._CENA;
			}
			set
			{
				if ((this._CENA != value))
				{
					this.OnCENAChanging(value);
					this.SendPropertyChanging();
					this._CENA = value;
					this.SendPropertyChanged("CENA");
					this.OnCENAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ZLECENIE")]
	public partial class ZLECENIE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _IMIE;
		
		private string _NAZWISKO;
		
		private string _MAIL;
		
		private System.Nullable<int> _TEL;
		
		private System.Nullable<System.DateTime> _DATA_ZLECENIA;
		
		private string _MIASTO;
		
		private string _ADRES;
		
		private System.Nullable<int> _RZECZOZNAWCA_ID;
		
		private System.Nullable<int> _CENNIK_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnIMIEChanging(string value);
    partial void OnIMIEChanged();
    partial void OnNAZWISKOChanging(string value);
    partial void OnNAZWISKOChanged();
    partial void OnMAILChanging(string value);
    partial void OnMAILChanged();
    partial void OnTELChanging(System.Nullable<int> value);
    partial void OnTELChanged();
    partial void OnDATA_ZLECENIAChanging(System.Nullable<System.DateTime> value);
    partial void OnDATA_ZLECENIAChanged();
    partial void OnMIASTOChanging(string value);
    partial void OnMIASTOChanged();
    partial void OnADRESChanging(string value);
    partial void OnADRESChanged();
    partial void OnRZECZOZNAWCA_IDChanging(System.Nullable<int> value);
    partial void OnRZECZOZNAWCA_IDChanged();
    partial void OnCENNIK_IDChanging(System.Nullable<int> value);
    partial void OnCENNIK_IDChanged();
    #endregion
		
		public ZLECENIE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMIE", DbType="VarChar(50)")]
		public string IMIE
		{
			get
			{
				return this._IMIE;
			}
			set
			{
				if ((this._IMIE != value))
				{
					this.OnIMIEChanging(value);
					this.SendPropertyChanging();
					this._IMIE = value;
					this.SendPropertyChanged("IMIE");
					this.OnIMIEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAZWISKO", DbType="VarChar(50)")]
		public string NAZWISKO
		{
			get
			{
				return this._NAZWISKO;
			}
			set
			{
				if ((this._NAZWISKO != value))
				{
					this.OnNAZWISKOChanging(value);
					this.SendPropertyChanging();
					this._NAZWISKO = value;
					this.SendPropertyChanged("NAZWISKO");
					this.OnNAZWISKOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAIL", DbType="VarChar(50)")]
		public string MAIL
		{
			get
			{
				return this._MAIL;
			}
			set
			{
				if ((this._MAIL != value))
				{
					this.OnMAILChanging(value);
					this.SendPropertyChanging();
					this._MAIL = value;
					this.SendPropertyChanged("MAIL");
					this.OnMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEL", DbType="Int")]
		public System.Nullable<int> TEL
		{
			get
			{
				return this._TEL;
			}
			set
			{
				if ((this._TEL != value))
				{
					this.OnTELChanging(value);
					this.SendPropertyChanging();
					this._TEL = value;
					this.SendPropertyChanged("TEL");
					this.OnTELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_ZLECENIA", DbType="Date")]
		public System.Nullable<System.DateTime> DATA_ZLECENIA
		{
			get
			{
				return this._DATA_ZLECENIA;
			}
			set
			{
				if ((this._DATA_ZLECENIA != value))
				{
					this.OnDATA_ZLECENIAChanging(value);
					this.SendPropertyChanging();
					this._DATA_ZLECENIA = value;
					this.SendPropertyChanged("DATA_ZLECENIA");
					this.OnDATA_ZLECENIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MIASTO", DbType="VarChar(50)")]
		public string MIASTO
		{
			get
			{
				return this._MIASTO;
			}
			set
			{
				if ((this._MIASTO != value))
				{
					this.OnMIASTOChanging(value);
					this.SendPropertyChanging();
					this._MIASTO = value;
					this.SendPropertyChanged("MIASTO");
					this.OnMIASTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRES", DbType="VarChar(100)")]
		public string ADRES
		{
			get
			{
				return this._ADRES;
			}
			set
			{
				if ((this._ADRES != value))
				{
					this.OnADRESChanging(value);
					this.SendPropertyChanging();
					this._ADRES = value;
					this.SendPropertyChanged("ADRES");
					this.OnADRESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RZECZOZNAWCA_ID", DbType="Int")]
		public System.Nullable<int> RZECZOZNAWCA_ID
		{
			get
			{
				return this._RZECZOZNAWCA_ID;
			}
			set
			{
				if ((this._RZECZOZNAWCA_ID != value))
				{
					this.OnRZECZOZNAWCA_IDChanging(value);
					this.SendPropertyChanging();
					this._RZECZOZNAWCA_ID = value;
					this.SendPropertyChanged("RZECZOZNAWCA_ID");
					this.OnRZECZOZNAWCA_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CENNIK_ID", DbType="Int")]
		public System.Nullable<int> CENNIK_ID
		{
			get
			{
				return this._CENNIK_ID;
			}
			set
			{
				if ((this._CENNIK_ID != value))
				{
					this.OnCENNIK_IDChanging(value);
					this.SendPropertyChanging();
					this._CENNIK_ID = value;
					this.SendPropertyChanged("CENNIK_ID");
					this.OnCENNIK_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RZECZOZNAWCA")]
	public partial class RZECZOZNAWCA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _NR;
		
		private string _IMIE;
		
		private string _NAZWISKO;
		
		private string _MAIL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNRChanging(System.Nullable<int> value);
    partial void OnNRChanged();
    partial void OnIMIEChanging(string value);
    partial void OnIMIEChanged();
    partial void OnNAZWISKOChanging(string value);
    partial void OnNAZWISKOChanged();
    partial void OnMAILChanging(string value);
    partial void OnMAILChanged();
    #endregion
		
		public RZECZOZNAWCA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NR", DbType="Int")]
		public System.Nullable<int> NR
		{
			get
			{
				return this._NR;
			}
			set
			{
				if ((this._NR != value))
				{
					this.OnNRChanging(value);
					this.SendPropertyChanging();
					this._NR = value;
					this.SendPropertyChanged("NR");
					this.OnNRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMIE", DbType="VarChar(50)")]
		public string IMIE
		{
			get
			{
				return this._IMIE;
			}
			set
			{
				if ((this._IMIE != value))
				{
					this.OnIMIEChanging(value);
					this.SendPropertyChanging();
					this._IMIE = value;
					this.SendPropertyChanged("IMIE");
					this.OnIMIEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAZWISKO", DbType="VarChar(50)")]
		public string NAZWISKO
		{
			get
			{
				return this._NAZWISKO;
			}
			set
			{
				if ((this._NAZWISKO != value))
				{
					this.OnNAZWISKOChanging(value);
					this.SendPropertyChanging();
					this._NAZWISKO = value;
					this.SendPropertyChanged("NAZWISKO");
					this.OnNAZWISKOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAIL", DbType="VarChar(50)")]
		public string MAIL
		{
			get
			{
				return this._MAIL;
			}
			set
			{
				if ((this._MAIL != value))
				{
					this.OnMAILChanging(value);
					this.SendPropertyChanging();
					this._MAIL = value;
					this.SendPropertyChanged("MAIL");
					this.OnMAILChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
